apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: test-argocd
spec:
  project: test-argocd-project

  source:
    repoURL: https://github.com/cclgwu/argocd-lab.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: in-cluster
    namespace: test-argocd

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
